from __future__ import annotations

"""Generate Git commit messages using Google's Gemini via the google-genai SDK."""

import os
from typing import Final, Any
from google import genai

from ._llm_common import (
    build_system_prompt,
    resolve_language,
    build_combined_prompt,
    CommitMessageResult,
)

_DEFAULT_MODEL: Final[str] = "gemini-2.5-flash"


def _resolve_model(*, model: str | None) -> str:
    """Resolve Gemini model name with environment fallbacks."""
    return (
        model
        or os.environ.get("GIT_COMMIT_MESSAGE_GEMINI_MODEL")
        or os.environ.get("GIT_COMMIT_MESSAGE_MODEL")
        or os.environ.get("GOOGLE_GENAI_MODEL")
        or _DEFAULT_MODEL
    )


def _generate_with_fallback(
    *,
    client: genai.Client,
    model: str,
    system_instruction: str,
    user_input: str,
):
    """Call google-genai, trying Responses API first, then legacy generate_content.

    Returns a tuple of (text, raw_response).
    """
    responses: Any = getattr(client, "responses", None)
    if responses is not None:
        resp = responses.generate(
            model=model,
            system_instruction=system_instruction,
            input=user_input,
        )
        text = (getattr(resp, "output_text", "") or "").strip()
        return text, resp

    models: Any = getattr(client, "models", None)
    if models is None:
        raise RuntimeError("google-genai Client has neither 'responses' nor 'models' attribute")
    resp = models.generate_content(
        model=model,
        contents=[{"role": "user", "parts": [{"text": user_input}]}],
        system_instruction=system_instruction,
    )
    text = (getattr(resp, "text", "") or getattr(resp, "output_text", "") or "").strip()
    return text, resp


def generate_commit_message(
    *,
    diff: str,
    hint: str | None,
    model: str | None,
    single_line: bool = False,
    subject_max: int | None = None,
    language: str | None = None,
) -> str:
    """Return a commit message generated by Gemini."""
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("The GOOGLE_API_KEY environment variable is required.")
    client = genai.Client(api_key=api_key)

    chosen_model = _resolve_model(model=model)
    chosen_language = resolve_language(language=language)
    system_instruction = build_system_prompt(
        single_line=single_line,
        subject_max=subject_max,
        language=chosen_language,
    )
    user_input = build_combined_prompt(diff=diff, hint=hint)

    text, _resp = _generate_with_fallback(
        client=client,
        model=chosen_model,
        system_instruction=system_instruction,
        user_input=user_input,
    )
    if not text:
        raise RuntimeError("An empty commit message was generated.")
    return text


def generate_commit_message_with_info(
    *,
    diff: str,
    hint: str | None,
    model: str | None,
    single_line: bool = False,
    subject_max: int | None = None,
    language: str | None = None,
) -> CommitMessageResult:
    """Return commit message plus usage/debug metadata (best-effort across versions)."""
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("The GOOGLE_API_KEY environment variable is required.")
    client = genai.Client(api_key=api_key)

    chosen_model = _resolve_model(model=model)
    chosen_language = resolve_language(language=language)
    system_instruction = build_system_prompt(
        single_line=single_line,
        subject_max=subject_max,
        language=chosen_language,
    )
    user_input = build_combined_prompt(diff=diff, hint=hint)

    response_text, resp = _generate_with_fallback(
        client=client,
        model=chosen_model,
        system_instruction=system_instruction,
        user_input=user_input,
    )
    if not response_text:
        raise RuntimeError("An empty commit message was generated.")

    response_id = getattr(resp, "id", None)
    usage = getattr(resp, "usage_metadata", None)

    prompt_tokens = None
    completion_tokens = None
    total_tokens = None
    if usage is not None:
        # Try multiple attribute names to cover differing SDK versions.
        prompt_tokens = getattr(usage, "input_tokens", None) or getattr(usage, "prompt_token_count", None)
        completion_tokens = getattr(usage, "output_tokens", None) or getattr(usage, "candidates_token_count", None)
        total_tokens = getattr(usage, "total_tokens", None) or getattr(usage, "total_token_count", None)

    return CommitMessageResult(
        message=response_text,
        model=chosen_model,
        prompt=user_input,
        response_text=response_text,
        response_id=response_id,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=total_tokens,
    )
