"""OpenAI provider implementation.

This module contains OpenAI-specific Responses and Chat Completions calls.
Provider-agnostic orchestration/prompt logic lives in `_llm.py`.
"""

from __future__ import annotations

from openai import OpenAI
from openai.types.responses import Response
from os import environ
from typing import ClassVar
from urllib.parse import urlsplit

from ._llm import LLMTextResult, LLMUsage


class OpenAIResponsesProvider:
    __slots__ = (
        "_client",
        "_api",
    )

    name: ClassVar[str] = "openai"

    def __init__(
        self,
        /,
        *,
        api_key: str | None = None,
        host: str | None = None,
        api: str | None = None,
    ) -> None:
        self._api = api or environ.get("GIT_COMMIT_MESSAGE_OPENAI_API") or "responses"
        if self._api not in ("responses", "chat-completions"):
            raise ValueError("The OpenAI API must be 'responses' or 'chat-completions'.")

        base_url = host or environ.get("OPENAI_BASE_URL")
        key = api_key or environ.get("OPENAI_API_KEY")
        if not key:
            if base_url and urlsplit(base_url).hostname != "api.openai.com":
                # Local compatible servers can operate without authentication.
                key = "unused"
            else:
                raise RuntimeError("The OPENAI_API_KEY environment variable is required.")
        self._client = OpenAI(api_key=key, base_url=base_url)

    def count_tokens(
        self,
        /,
        *,
        model: str,
        text: str,
    ) -> int:
        if self._api == "chat-completions":
            raise RuntimeError(
                "Token counting is unavailable for the Chat Completions API. "
                "Use `--chunk-tokens 0` (default) or `--chunk-tokens -1` to disable summarisation."
            )
        try:
            resp = self._client.responses.input_tokens.count(
                model=model,
                input=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "input_text",
                                "text": text,
                            }
                        ],
                    }
                ],
            )
        except Exception as exc:
            raise RuntimeError(
                "Token counting failed for the OpenAI provider. "
                "Try `--chunk-tokens 0` (default) or `--chunk-tokens -1` to disable summarisation."
            ) from exc

        prompt_tokens = getattr(resp, "input_tokens", None)
        if not isinstance(prompt_tokens, int):
            raise RuntimeError(
                "Token counting returned an unexpected response from the OpenAI provider. "
                "Try `--chunk-tokens 0` (default) or `--chunk-tokens -1` to disable summarisation."
            )

        return prompt_tokens

    def generate_text(
        self,
        /,
        *,
        model: str,
        instructions: str,
        user_text: str,
    ) -> LLMTextResult:
        if self._api == "chat-completions":
            return self._generate_chat_text(
                model=model,
                instructions=instructions,
                user_text=user_text,
            )

        resp: Response = self._client.responses.create(
            model=model,
            instructions=instructions,
            input=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": user_text,
                        }
                    ],
                }
            ],
        )

        text: str = (resp.output_text or "").strip()
        if not text:
            raise RuntimeError("An empty response text was generated by the provider.")

        usage: LLMUsage | None = None
        if resp.usage is not None:
            usage = LLMUsage(
                prompt_tokens=resp.usage.input_tokens,
                completion_tokens=resp.usage.output_tokens,
                total_tokens=resp.usage.total_tokens,
            )

        return LLMTextResult(
            text=text,
            response_id=resp.id,
            usage=usage,
        )

    def _generate_chat_text(
        self,
        /,
        *,
        model: str,
        instructions: str,
        user_text: str,
    ) -> LLMTextResult:
        response = self._client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": instructions},
                {"role": "user", "content": user_text},
            ],
            stream=False,
        )
        text = (response.choices[0].message.content or "").strip() if response.choices else ""
        if not text:
            raise RuntimeError("An empty response text was generated by the provider.")

        usage: LLMUsage | None = None
        if response.usage is not None:
            usage = LLMUsage(
                prompt_tokens=response.usage.prompt_tokens,
                completion_tokens=response.usage.completion_tokens,
                total_tokens=response.usage.total_tokens,
            )

        return LLMTextResult(
            text=text,
            response_id=response.id,
            usage=usage,
        )
