"""Text generation through an OpenAI-compatible Chat Completions API."""

from __future__ import annotations

from os import environ
from typing import ClassVar

from openai import OpenAI
from openai.types.chat import ChatCompletionMessageParam

from ._config import resolve_provider_url
from ._llm import LLMTextResult, LLMUsage


class OpenAICompatibleProvider:
    """Use an explicitly configured API base URL for chat completions."""

    __slots__ = ("_client",)

    name: ClassVar[str] = "openai-compatible"

    def __init__(
        self,
        /,
        *,
        url: str | None = None,
        host: str | None = None,
    ) -> None:
        self._client = OpenAI(
            base_url=resolve_provider_url(self.name, url=url, host=host),
            api_key=environ.get("OPENAI_COMPATIBLE_API_KEY") or "openai-compatible",
        )

    def generate_text(
        self,
        /,
        *,
        model: str,
        instructions: str,
        user_text: str,
    ) -> LLMTextResult:
        """Generate text and retain response metadata when supplied."""

        messages: list[ChatCompletionMessageParam] = [
            {"role": "system", "content": instructions},
            {"role": "user", "content": user_text},
        ]
        resp = self._client.chat.completions.create(model=model, messages=messages)
        text = (resp.choices[0].message.content or "").strip() if resp.choices else ""
        if not text:
            raise RuntimeError("An empty response text was generated by the provider.")

        usage = None
        if resp.usage is not None:
            usage = LLMUsage(
                prompt_tokens=resp.usage.prompt_tokens,
                completion_tokens=resp.usage.completion_tokens,
                total_tokens=resp.usage.total_tokens,
            )
        return LLMTextResult(text=text, response_id=resp.id, usage=usage)

    def count_tokens(
        self,
        /,
        *,
        model: str,
        text: str,
    ) -> int:
        raise RuntimeError(
            "Token counting is not supported for the openai-compatible provider. "
            "Use --chunk-tokens 0 or --chunk-tokens -1."
        )
